### PR TITLE
fix: resolve #56 via checking for array type

### LINKED ISSUE #56: [Bug]: error on hitting `Esc` button
When a sonner component is used in page, whenever user hits escape button from keyboard, an error is logged in console:

```
Uncaught TypeError: te.contains is not a function
```

Reproduction Steps:
1. go to [sooner](https://vue-sonner.vercel.app/) demo page
2. focus the page if not focued
3. git `esc` button
4. open console tab in browser

### PR DESCRIPTION
**Pull request by Saeid-Za**
Whenever template binding is used in a `v-for`, the result could be an array or a single item depending on how many iterations the `v-for` is run.

### CODE REVIEW

File: packages/Toaster.vue [hunk 1]
```diff
@@ -358,16 +358,16 @@ watchEffect((onInvalidate) => {
       (key) => (event as any)[key] || event.code === key
     )
 
+    const listRefItem = Array.isArray(listRef.value) ? listRef.value.at(0) : listRef.value
```
Comment (xiaoluoboding) [inline packages/Toaster.vue:361]: It seems like the `.at` syntax cannot be used in the repo. Can we use `listRef.value[0]` instead?

**Review by xiaoluoboding — CHANGES_REQUESTED** [review]

File: packages/Toaster.vue (hunk 1 above)
Comment (Saeid-Za) [reply packages/Toaster.vue:361]: Sure, no problem.

**Review by xiaoluoboding — APPROVED** [review]
LGTM
